package controller.server;

public enum RequestEnum {
    LOGIN,
    SIGN_UP,
    LOGOUT,
    SHOP_BUY_AND_SELL,
    SHOP_SEARCH,
    SHOP_BUY,
    SHOP_CARDS,
    SHOP_SELL,
    COLLECTION_SHOW,
    COLLECTION_DECKS,
    COLLECTION_NEW_DECK,
    COLLECTION_SELECT_DECK,
    COLLECTION_SELECT_MAIN_DECK,
    COLLECTION_EXPORT,
    COLLECTION_IMPORT,
    COLLECTION_ADD_CARD_TO_DECK,
    CHAT,
    ENTER_CHAT,
    SHOP_HELP,
    SHOP_ITEMS

}
