package IDK;

public enum BattleRequestType {
    GAME_GAME_INFO,
    GAME_SHOW_MY_MINION,
    GAME_SHOW_OPPONENT_MINION,
    GAME_SHOW_CARD_INFO,
    GAME_SELECT_CARD_ID,
    GAME_MOVE,
    GAME_ATTACK,
    GAME_ATTACK_COMBO,
    GAME_USE_SPECIAL_POWER,
    GAME_SHOW_HAND,
    GAME_INSERT,
    GAME_END_TURN,
    GAME_SHOW_COLLECTABLES,
    GAME_SELECT_COLLECTABLE,
    GAME_ITEM_SHOW_INFO,
    GAME_ITEM_uSE,
    GAME_SHOW_NEXT_CARD,
    GAME_ENTER_GRAVE_YARD,
    GAME_GRAVE_YARD_SHOW_INFO,
    GAME_GRAVE_YARD_SHOW_CARDS,
    GAME_GRAVE_YARD_EXIT,
    GAME_HELP,
    GAME_END_GAME,
    GAME_EXIT,
    GAME_SHOW_MENU;
}
