package IDK;

public enum  RequestType {
    COLLECTION_SHOW,
    COLLECTION_EXIT,
    COLLECTION_SEARCH_CARD,
    COLLECTION_SAVE,
    COLLECTION_CREATE_DECK,
    COLLECTION_DELETE_DECK,
    COLLECTION_ADD_CARD_TO_DECK,
    COLLECTION_REMOVE_CARD_FROM_DECK,
    COLLECTION_VALIDATE_DECK,
    COLLECTION_SELECT_DECK,
    COLLECTION_SHOW_ALL_DECKS,
    COLLECTION_SHOW_DECK,
    COLLECTION_HELP;
}
